server:
  port: 8080

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HabitForge_DB
    username: postgres
    password: felipevictor5120_
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true
    main:
      web-development-type: servlet